import React from "react";

import ShieldIcon from "./n_shield.png";
// import SchwarzLogo from "./Schwarz-logo.svg"
import OtpInput from "./Otpinput";
import {Link} from "react-router-dom";

const Otpscreen = () => {

    return (
        <div className={"parent-container m-auto grid grid-cols-2 max-md:grid-cols-1 h-screen"}>
            <div className={"tile h-full"}>
                <div className={"flex flex-col items-center justify-center h-full"}>
                    <img src={ShieldIcon} className="shield-icon h-28" alt={"Security Icon"}/>

                <h1 className="text-2xl max-md:text-xl font-bold mb-[4px]">Authenticate your Account</h1>
                <p className="fade-text w-9/12 text-center">Enter the 6 digit code generated by your <span
                    className="text-blue font-medium hover:cursor-pointer">Google Authenticator</span> app to verify
                    your identity</p>
                <OtpInput/>
                <Link to={"/auth"} className="text-blue font-semibold  m-2 relative top-1 hover:cursor-pointer text-center">Unable
                    to reach Google Authenticator? Try another way</Link>
                </div>
            </div>

            <div className="bg-l_light_grey h-full block max-md:hidden">
                <h1 className="tile-marker h-full">Looping Simulation from Blender</h1>
            </div>
        </div>
    );
}
export default Otpscreen;